In [56]:
import pandas as pd

In [57]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [58]:
train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
test.head()

,id,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 359.3 MB

In [61]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Columns: 785 entries, id to pixel783
dtypes: int64(785)
memory usage: 29.9 MB

In [62]:
X=train.iloc[:,1:].values
y=train.iloc[:,1].values

In [63]:
#reshape data
X = X.reshape(X.shape[0], 28, 28)/255.0
X = X.reshape(X.shape[0], 28,28,1)

In [64]:
test=test.iloc[:,1:].values

In [65]:
test = test.reshape(test.shape[0], 28, 28)/255.0
test = test.reshape(test.shape[0], 28,28,1)

In [66]:
#import keras libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Convolution2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense,Dropout

In [67]:
#initialize
classifier=Sequential()

In [68]:
#layer1
classifier.add(Convolution2D(28,3,3,input_shape=(28,28,1),activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Dropout(0.25))

In [69]:
#layer2
classifier.add(Convolution2D(32,padding='same',kernel_size=3,activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

In [70]:
#layer3
classifier.add(Convolution2D(64,padding='same',kernel_size=3,activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

In [71]:
#flattening
classifier.add(Flatten())

In [72]:
classifier.add(Dense(units=128,activation='relu'))
classifier.add(Dropout(0.5))
classifier.add(Dense(units=10,activation='softmax'))

In [73]:
#compile
classifier.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [74]:
#fit model
classifier.fit(X, y, batch_size = 12, epochs = 20)

Train on 60000 samples
Epoch 1/20
60000/60000 [==============================] - 81s 1ms/sample - loss: 0.0036 - accuracy: 0.9998
Epoch 2/20
60000/60000 [==============================] - 87s 1ms/sample - loss: 4.6270e-08 - accuracy: 1.0000
Epoch 3/20
60000/60000 [==============================] - 90s 2ms/sample - loss: 1.9095e-08 - accuracy: 1.0000
Epoch 4/20
60000/60000 [==============================] - 77s 1ms/sample - loss: 1.1921e-11 - accuracy: 1.0000
Epoch 5/20
60000/60000 [==============================] - 82s 1ms/sample - loss: 3.9736e-12 - accuracy: 1.0000
Epoch 6/20
60000/60000 [==============================] - 67s 1ms/sample - loss: 3.9736e-12 - accuracy: 1.0000
Epoch 7/20
60000/60000 [==============================] - 77s 1ms/sample - loss: 3.9736e-12 - accuracy: 1.0000
Epoch 8/20
60000/60000 [==============================] - 82s 1ms/sample - loss: 7.9473e-12 - accuracy: 1.0000
Epoch 9/20
60000/60000 [==============================] - 83s 1ms/sample - loss: 1.4404e-09 - accuracy: 1.0000
Epoch 10/20
60000/60000 [==============================] - 86s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 11/20
60000/60000 [==============================] - 167s 3ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 12/20
60000/60000 [==============================] - 123s 2ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 13/20
60000/60000 [==============================] - 81s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 14/20
60000/60000 [==============================] - 63s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 15/20
60000/60000 [==============================] - 88s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 16/20
60000/60000 [==============================] - 63s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 17/20
60000/60000 [==============================] - 75s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 18/20
60000/60000 [==============================] - 85s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 19/20
60000/60000 [==============================] - 88s 1ms/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 20/20
60000/60000 [==============================] - 96s 2ms/sample - loss: 0.0000e+00 - accuracy: 1.0000

In [75]:
y_pred = classifier.predict(test)

In [76]:
import numpy as np
results = np.argmax(y_pred,axis = 1)
data_out = pd.DataFrame({'id': range(len(test)), 'label': results})
data_out.to_csv('try.csv', index = None)